### ISSUE TITLE
Invalid authentication

### ISSUE THREAD

**Issue by cwecki** [Jarnsen/ha-xsense-component_test#10]
### Voraussetzungen / Prerequisites

- [X] Ich bestätige, dass ich Home Assistant Version 2024.10.1 oder höher verwende.  
      I confirm that I am using Home Assistant version 2024.10.1 or higher.
- [X] Ich bestätige, dass ich die neueste Version der X-Sense-Integration installiert habe.  
      I confirm that I have installed the latest version of the X-Sense integration.
- [X] Ich bestätige, dass ich HACS Version 2.0 oder höher verwende.  
      I confirm that I am using HACS version 2.0 or higher.

### Versionsinformationen / Version Information

Bitte geben Sie die verwendeten Versionen an:  
Please specify the versions used:

- **Home Assistant Version** (z. B. 2024.10.1):  
  2024.10.4
- **X-Sense-Integration Version** (z. B. 1.0.13):  
1.0.13
- **HACS Version** (z. B. 2.0.0):  
2.0.1

### Beschreibung des Problems / Problem Description

*Beschreiben Sie das aufgetretene Problem detailliert.*  
*Describe the problem in detail.*

Ich habe die Integration über HACS installiert und neu gestartet.
Beim hinzufügen der Integration in Homeassistant erhalte ich dann "Invalid authentication"

### Schritte zur Reproduktion / Steps to Reproduce

1. Installation mit HACS und Neustart
2. Einstellungen -> Integrationen -> Integration Hinzufügen -> X-Sense
3. Logindaten eingeben (Logindaten sind mehrfach verifiziert und korrekt)

### Erwartetes Verhalten / Expected Behavior

*Beschreiben Sie, was Ihrer Meinung nach passieren sollte.*  
*Describe what you expected to happen.*

Die Anmeldung sollte erfolgreich verlaufen.

### Screenshots oder Logs / Screenshots or Logs

*Fügen Sie bei Bedarf relevante Screenshots oder Log-Dateien hinzu.*  
*Add relevant screenshots or logs if needed.*

![image](https://github.com/user-attachments/assets/314fbe38-82cd-4bb3-881c-d059db244372)

info: Mein Passwort ist 32 Zeichen lang und enthält #$ als Sonderzeichen. Falls dies relevant ist.

**Comment by Jarnsen** [comment]
Das deutet darauf hin das deine Zugangsdaten falsch sind, Email und Passwort aus dem 2. Account der xsense App nehmen, zur Not mal mit Hauptaccount prüfen.

**Comment by cwecki** [comment]
@Jarnsen 
Das habe ich ja direkt  ausgeschlossen. Die Zugangsdaten habe ich mehrfach validiert. Sie sind gültig und funktionieren.
Und sie sind von einem 2. Account.

**Comment by cwecki** [comment]
Ich konnte das Problem lösen.
xSense Passwörter dürfen maximal 20 Zeichen lang sein.

Die Registrierung eines neuen Benutzers und die Anmeldung an der App erlauben grundsätzlich Passwörter in beliebiger Länge. Daher hat der Login auch immer funktioniert.
Allerdings kürzt xSense das eingegebene Passwort in der App und bei der Registrierung anscheinend auf 20 Zeichen und nimmt nur die ersten 20 Zeichen. Das tut die Erweiterung hier anscheinend nicht. Daher kam es zu Loginproblemen.

**Comment by fioer9fjs** [comment]
Ich habe die Integration ebenfalls über HACS installiert und habe auch das o.g. Authentication-Problem. 
In der Zwischenzeit habe ich das Passwort auf 6 Zeichen reduziert, nur Kleinbuchstaben und Zahlen, keine Sonderzeichen.
Sowohl Passwort als auch User habe ich x-fach überprüft und bin mir ziemlich sicher, dass meine Eingaben keinen Tippfehler enthalten - Login via Copy&Paste aus dem Passwort-Manager in die X-Sense-Webseite tut nämlich tadellos.
Wo kann ich denn detailliertere Logs finden?

ha-xsense-component_test 1.0.16
Core 2025.4.1
Supervisor 2025.03.4
Operating System 15.1
Frontend 20250404.0
