### ISSUE TITLE
X-Sense Home Security configuration wizard will NOT start

### ISSUE THREAD

**Issue by Suprimos85** [Jarnsen/ha-xsense-component_test#12]
I installed the repository via HACS as in the youtube video.
After reboot i want to add the integration --> a popup winodws comes up and it says:
Please wait, the X-Sense Home Security configuration wizard will start

This stays there forever. Nothing happens....even after reboot.

X-sense
1.0.13

Core
2024.11.3
Supervisor
2024.11.4
Operating System
13.2
Frontend
20241106.2

**Comment by Jarnsen** [comment]
Pls Check your HACS Version, it Must be >2.xx. How many devices do you have? Pls deinstall all of X-Sense, reboot, Download , reboot, install, reboot host, configure the Integration.

**Comment by Suprimos85** [comment]
Hello, its HACS 2.0.1
Well in the X-Sense App I registered one homestation and one smokedetector...not more yet

**Comment by Suprimos85** [comment]
Funny fact - i just tried to do the config with my mobile phone homeassistant app and there it worked...it did not work from my pc (no adblocker eg installed)
