### ISSUE TITLE
Invalid handler specified

### ISSUE THREAD

**Issue by billouetaudrey** [Jarnsen/ha-xsense-component_test#6]
Hey,

after trying to add xsense device on HA, I have this error : 

"error from daemon in stream: Error grabbing logs: invalid character 'l' after object key:value pair"

Any idea please ?

Thanks

**Comment by Jarnsen** [comment]
How do install it? Wich Version of HA and xsense?

**Comment by billouetaudrey** [comment]
With HACS 
Core 2024.5.4 ( docker)
X-sense 1.0.13

Thanks

**Comment by Jarnsen** [comment]
You Need Minimum of ha 2024.10.1

**Comment by billouetaudrey** [comment]
Oh ok, lemme search how to update it.

Thanks

**Comment by Jarnsen** [comment]
The Problem is, there are many Updates later than 2024.10.0

**Comment by billouetaudrey** [comment]
Fixed, work like a charm : SC07-WX

Thanks

**Comment by Jarnsen** [comment]
You Are welcome
