### ISSUE TITLE
Error occurred loading flow for integration xsense: No module named 'xsense'

### ISSUE THREAD

**Issue by nashant** [Jarnsen/ha-xsense-component_test#7]
Hi. When trying to add this integration I get `Config flow could not be loaded: {"message":"Invalid handler specified"}`.
The logs show `Error occurred loading flow for integration xsense: No module named 'xsense'`.
I'm using the home assistant container

**Comment by NegativeFeedback** [comment]
I also am running into this issues installing from hacs

**Comment by Jarnsen** [comment]
How do install it? Wich Version of HA and xsense?

**Comment by nashant** [comment]
v1.0.13, but also tried an earlier version. Install from HACS, HomeAssistant version 2024.10, using container (docker) version

**Comment by nashant** [comment]
I've now got version 2024.11.1

**Comment by Jarnsen** [comment]
It is working?

**Comment by nashant** [comment]
Nope

**Comment by Jarnsen** [comment]
Is it posible to visit the Discord? Its easier

**Comment by vuminhkh** [comment]
Hello, I'm having the same issue, install custom repo from HACS and the same issue 

`2024-11-13 21:44:43.139 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration xsense: No module named 'xsense'`

Could we have the discussion here, it'll help other people also using the integration ? Thanks.

**Comment by vuminhkh** [comment]
Just FYI, I just did pip install python-xsense==0.0.13 inside my homeassistant container manually, and the integration is loading correctly. It looks like the dependency in your manifest file was not interpreted correctly by home assistant.

**Comment by vuminhkh** [comment]
After that, the integration has been loaded correctly and it's running fine, it's a home assistant bug and needs to be reported ? 
On another subject, I'm new to Xsense, i'm having some standalone smoke and CO detector, the wifi connection from those devices seem not to be active (at least all the time), the devices look offline on my wifi AP. I suppose it's to save energy ? The device will reconnect only when it needs to send notification or information about battery and device health from time to time ? Thanks a lot for your work, it's working very well your integration.

**Comment by Jarnsen** [comment]
With the wifi, I think Its correct because energy saving.

with the manifest, I will Test ist. Thx for reporting.

**Comment by nashant** [comment]
Also installed manually, working OK now. Is something broken with the HASS container install?

**Comment by Jarnsen** [comment]
I have thoroughly reviewed the integration process:

1. **Removal of Existing Integration:**
   - Deleted the X-Sense integration from Home Assistant.
   - Verified the absence of related entries in the `custom_components` directory.

2. **Uninstallation via HACS:**
   - Completely removed the integration from HACS, including the repository.

3. **System Restart:**
   - Performed a hardware restart.
   - Confirmed that no traces of X-Sense remained on the system.

4. **Reinstallation Following GitHub Instructions:**
   - Downloaded the integration through HACS.
   - Restarted Home Assistant.
   - Installed the integration via the Devices & Services section.

The entire process completed without issues. The previously mentioned error could not be reproduced. Both HACS and Home Assistant are updated to their latest versions.

**Comment by nashant** [comment]
Is that with the container install of home assistant?

**Comment by Jarnsen** [comment]
no, i use the OS instalation of HA

**Comment by nashant** [comment]
I think we can close this issue. Upstream issue [here](https://github.com/home-assistant/core/issues/127966). Fixed by setting `PYTHONPATH` to `/config/deps`

**Comment by Jarnsen** [comment]
Thanks for the answer
