### ISSUE TITLE
Impossible to configure

### ISSUE THREAD

**Issue by lguillaumont** [Jarnsen/ha-xsense-component_test#8]
- [x] HACS Running
- [x] Downloaded and installed X-sense

When trying to add a device:

```
Error
Config flow could not be loaded: {"message":"Invalid handler specified"}
```

I see /hass-config/custom_components/xsense/config_flow.py
But no .yaml file in /hass-config/custom_components/xsense/

Any idea why?

**Comment by Jarnsen** [comment]
Yes, I know the misstake,
![IMG_2482](https://github.com/user-attachments/assets/a9a61330-0b29-480d-8f02-c9d323319a3c)

you Need HA 2024.10.1 or later, later than 2024.10.0 there are a lot of changes in HA.

**Comment by lguillaumont** [comment]
🤦‍♂️🙏👌

--
Léonard Guillaumont
FR +33 6 95 25 20 67

**Comment by Jarnsen** [comment]
you are welcome

**Comment by Jarnsen** [comment]
let me know, if it works

**Comment by Jarnsen** [comment]
Is it working???

**Comment by lguillaumont** [comment]
Hello,

I won't have time those days for an update.

I will keep you posted once done 👌

--
Léonard Guillaumont
FR +33 6 95 25 20 67
